"use client";
import {useMemo,useState} from "react";
import {dailyActions,type DailyAction} from "../lib/daily-actions";
import {routeQuestion,specialistAgents,type SpecialistAgent} from "../lib/agents";
import {resolveSituations} from "../lib/resolve";
const starters=["Rédige un email après une visite sans retour","Crée une annonce pour un appartement lumineux à Bruxelles","Mon vendeur trouve mes honoraires trop élevés","Vérifie si le PEB doit apparaître dans une annonce en Wallonie"];
export default function Home(){
const[question,setQuestion]=useState("");const[agent,setAgent]=useState<SpecialistAgent|null>(null);const[submitted,setSubmitted]=useState(false);const[copied,setCopied]=useState(false);
const matches=useMemo(()=>resolveSituations(question).slice(0,3),[question]);
function ask(value=question){const clean=value.trim();if(!clean)return;setQuestion(clean);setAgent(routeQuestion(clean));setSubmitted(true)}
function startAction(action:DailyAction){const selected=specialistAgents.find(item=>item.id===action.agentId)??specialistAgents[0];setAgent(selected);setQuestion(action.prompt);setSubmitted(false);window.setTimeout(()=>document.getElementById("main-question")?.focus(),0)}
async function copyPrompt(){await navigator.clipboard.writeText(question);setCopied(true);window.setTimeout(()=>setCopied(false),1200)}
return <main className="appShell">
<header className="topbar"><button className="logo" onClick={()=>{setSubmitted(false);setAgent(null);setQuestion("")}}>IB</button><div className="brand"><strong>ImmoBoost™ Belgique</strong><span>Votre équipe IA immobilière.</span></div><span className="market">🇧🇪 Belgique · FR</span></header>
<section className="hero"><span className="eyebrow">UN SEUL POINT D’ENTRÉE</span><h1>Qu’est-ce que vous devez faire maintenant&nbsp;?</h1><p>Écrivez comme vous parleriez à un collègue. ImmoBoost choisit le bon agent spécialisé, sans menu compliqué.</p><div className="askBox"><textarea id="main-question" value={question} onChange={e=>{setQuestion(e.target.value);setSubmitted(false)}} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Ex. Rédige un email pour relancer un vendeur après l’estimation…"/><button onClick={()=>ask()}>Envoyer →</button></div><div className="starterRow">{starters.map(starter=><button key={starter} onClick={()=>ask(starter)}>{starter}</button>)}</div></section>
{!submitted&&<section className="workspace"><div className="sectionTitle"><span>AU QUOTIDIEN</span><h2>Que voulez-vous produire&nbsp;?</h2><p>Chaque bouton ouvre directement le bon spécialiste avec une demande déjà préparée.</p></div><div className="actionGrid">{dailyActions.map(action=><button className="actionCard" key={action.id} onClick={()=>startAction(action)}><span className="actionIcon">{action.icon}</span><div><strong>{action.title}</strong><small>{action.description}</small></div><b>→</b></button>)}</div></section>}
{submitted&&agent&&<section className="conversation"><button className="backLink" onClick={()=>setSubmitted(false)}>← Modifier la demande</button><div className="routeBanner"><span>{agent.icon}</span><div><small>AGENT SÉLECTIONNÉ AUTOMATIQUEMENT</small><strong>{agent.name}</strong><p>{agent.scope}</p></div></div><article className="answerCard"><div className="answerHead"><span className={`trust ${agent.trust}`}>{agent.trust==="official"?"Sources officielles requises":agent.trust==="mixed"?"Métier + vérification":"Expertise métier"}</span><small>Question reçue</small></div><blockquote>{question}</blockquote><div className="prototypeNotice"><strong>Connexion IA à finaliser</strong><p>Le bon agent est déjà sélectionné. Cette zone accueillera sa vraie réponse conversationnelle, les actions à copier et les sources officielles quand elles sont nécessaires.</p></div><div className="answerActions"><button onClick={copyPrompt}>{copied?"Copié ✓":"Copier la demande"}</button><button className="secondary" onClick={()=>setSubmitted(false)}>Ajouter du contexte</button></div></article>{matches.length>0&&<div className="knownSolutions"><div className="sectionTitle compact"><span>SOLUTIONS DÉJÀ VALIDÉES</span><h2>ImmoBoost a aussi trouvé ceci</h2></div>{matches.map(match=><div className="solutionRow" key={match.id}><span>{match.kind==="situation"?"⚡":match.resource.icon}</span><div><strong>{match.title}</strong><small>{match.description}</small></div></div>)}</div>}</section>}
<footer className="footerNote"><strong>ImmoBoost ne mélange pas les pays.</strong><span>Cette version charge uniquement les agents, contenus et sources de la Belgique.</span></footer></main>}
