export type SeoSituation = {
  slug: string;
  fieldId: string;
  category: string;
  title: string;
  searchTitle: string;
  description: string;
  question: string;
  diagnosis: string;
  recommendation: string;
  immediateAction: string;
  steps: string[];
  message: string;
  followUp: { when: string; objective: string };
  mistakes: string[];
  source?: { title: string; authority: string; url: string; checkedAt: string };
};

export const seoSituations: SeoSituation[] = [
  {
    slug: "vendeur-refuse-baisser-prix",
    fieldId: "BE-001",
    category: "Vendeur",
    title: "Le vendeur refuse de baisser son prix",
    searchTitle: "Vendeur qui refuse de baisser son prix : plan d’action",
    description: "Une méthode concrète pour aider un vendeur à revoir son prix sans confrontation : diagnostic, message, rendez-vous et suivi.",
    question: "Comment convaincre un vendeur de revoir son prix sans abîmer la relation ?",
    diagnosis: "Le blocage vient rarement du prix seul. Le vendeur protège souvent son estimation initiale, son projet futur ou la confiance qu’il a placée dans l’agent. Une pression directe provoque donc de la résistance.",
    recommendation: "Proposer un point de décision fondé sur les signaux du marché plutôt qu’une demande de baisse isolée.",
    immediateAction: "Préparer une synthèse d’une page : demandes reçues, visites, retours, concurrence active et conséquence probable du maintien du prix.",
    steps: [
      "Distinguer les faits observables des impressions.",
      "Montrer l’écart entre l’objectif du vendeur et la réaction actuelle du marché.",
      "Présenter deux scénarios : maintien temporaire avec date de réévaluation, ou repositionnement maintenant.",
      "Faire choisir une prochaine décision et la dater.",
    ],
    message: "Bonjour [Prénom], j’ai préparé un point très concret sur les réactions obtenues depuis la mise en vente. Mon objectif n’est pas de vous pousser à baisser, mais de vous montrer ce que le marché nous dit aujourd’hui et les deux options possibles. Pouvons-nous prendre 15 minutes demain ?",
    followUp: { when: "Sous 24 heures", objective: "Obtenir un rendez-vous de décision, pas négocier le prix par message." },
    mistakes: ["Dire simplement que le bien est trop cher.", "Comparer sans tenir compte des différences entre les biens.", "Attendre plusieurs semaines sans fixer de date de réévaluation."],
  },
  {
    slug: "vendeur-consulte-plusieurs-agences",
    fieldId: "BE-002",
    category: "Mandat",
    title: "Le vendeur consulte plusieurs agences",
    searchTitle: "Vendeur qui consulte plusieurs agences : quelle relance ?",
    description: "La relance à utiliser après une estimation lorsque le propriétaire veut encore comparer plusieurs agences immobilières.",
    question: "Que répondre à un propriétaire qui veut rencontrer d’autres agences avant de signer ?",
    diagnosis: "Le vendeur ne rejette pas nécessairement l’agent. Il cherche surtout à réduire son risque et à comparer la méthode, les honoraires ou la promesse de prix.",
    recommendation: "Ne pas combattre la comparaison. Donner au vendeur une grille simple pour comparer la qualité d’exécution, puis fixer un retour court.",
    immediateAction: "Envoyer un résumé personnalisé du rendez-vous avec les trois décisions importantes et proposer un appel de dix minutes après ses autres rencontres.",
    steps: [
      "Reformuler l’objectif réel du vendeur.",
      "Rappeler la stratégie proposée sans refaire toute la présentation.",
      "Donner trois critères de comparaison : méthode, suivi et capacité à défendre le prix.",
      "Bloquer un créneau de retour précis.",
    ],
    message: "Bonjour [Prénom], merci pour notre échange. Je comprends votre souhait de comparer. Pour que cela vous aide vraiment, regardez surtout la méthode de lancement, le suivi prévu après chaque visite et la façon dont l’agence défendra votre prix. Je vous envoie mon plan résumé et je vous propose un bref point [jour] à [heure].",
    followUp: { when: "48 heures après le rendez-vous", objective: "Faire comparer les méthodes plutôt que les promesses." },
    mistakes: ["Critiquer les agences concurrentes.", "Relancer sans apporter de nouvel élément.", "Laisser le prochain contact sans date."],
  },
  {
    slug: "obtenir-mandat-exclusif",
    fieldId: "BE-016",
    category: "Mandat",
    title: "Obtenir un mandat exclusif sans forcer",
    searchTitle: "Comment obtenir un mandat exclusif immobilier ?",
    description: "Une méthode simple pour présenter l’exclusivité comme un plan de responsabilité et non comme une contrainte imposée au vendeur.",
    question: "Comment défendre l’exclusivité sans donner au vendeur l’impression de perdre sa liberté ?",
    diagnosis: "Le refus traduit souvent une peur de dépendre d’une seule agence. Répéter les avantages génériques de l’exclusivité ne répond pas à cette peur.",
    recommendation: "Relier l’exclusivité à des engagements d’exécution visibles, datés et contrôlables par le vendeur.",
    immediateAction: "Présenter une feuille de route des quatorze premiers jours avec les livrables, les points de contrôle et la fréquence des comptes rendus.",
    steps: [
      "Demander ce que le vendeur craint concrètement avec une seule agence.",
      "Associer chaque crainte à un engagement mesurable.",
      "Montrer qui est responsable de chaque action de lancement.",
      "Faire valider la méthode avant de reparler du mandat.",
    ],
    message: "Votre inquiétude est légitime : une exclusivité sans engagement précis serait inconfortable. Je vous propose donc de juger l’exclusivité sur un plan concret : lancement, diffusion, retours de visites et point de décision. Voici exactement ce que je m’engage à livrer et quand.",
    followUp: { when: "À la fin du rendez-vous", objective: "Obtenir un accord sur le plan d’exécution avant la signature." },
    mistakes: ["Présenter l’exclusivité comme une faveur faite à l’agence.", "Promettre un prix ou un délai impossible à garantir.", "Aborder les clauses sans vérifier le contrat et le cadre applicable."],
    source: { title: "Guidelines sur l’intermédiation immobilière", authority: "Institut professionnel des agents immobiliers", url: "https://www.ipi.be/actualites/articles/le-spf-economie-publie-de-nouveaux-guidelines-sur-lintermediation-immobiliere", checkedAt: "2026-07-17" },
  },
  {
    slug: "acquereur-ne-repond-plus-apres-visite",
    fieldId: "BE-004",
    category: "Après-visite",
    title: "L’acquéreur ne répond plus après une visite",
    searchTitle: "Acquéreur sans réponse après visite : message de relance",
    description: "Un message de relance après visite qui cherche une décision utile sans harceler l’acquéreur ni envoyer une formule générique.",
    question: "Quel message envoyer lorsqu’un acquéreur ne répond plus après la visite ?",
    diagnosis: "Le silence peut signifier un manque d’intérêt, une comparaison en cours, une objection non formulée ou simplement une absence d’urgence. La relance doit faciliter une réponse courte.",
    recommendation: "Poser une seule question de décision et offrir une sortie claire.",
    immediateAction: "Envoyer un message contextualisé qui rappelle le bien et demande si le dossier doit rester actif.",
    steps: [
      "Rappeler un élément précis de la visite.",
      "Poser une seule question.",
      "Permettre une réponse simple : intéressé, hésitant ou à clôturer.",
      "Mettre à jour le suivi selon la réponse obtenue.",
    ],
    message: "Bonjour [Prénom], je reviens vers vous au sujet de la visite de [bien]. Vous aviez notamment réagi à [élément précis]. Souhaitez-vous que je garde votre recherche active sur ce bien, que nous clarifiions un point, ou puis-je clôturer ce suivi ?",
    followUp: { when: "Le lendemain de la visite, puis une dernière fois à J+3", objective: "Obtenir un statut exploitable plutôt qu’une longue réponse." },
    mistakes: ["Envoyer plusieurs questions dans le même message.", "Écrire seulement « avez-vous réfléchi ? ».", "Multiplier les relances sans nouvelle information."],
  },
  {
    slug: "repondre-offre-immobiliere-trop-basse",
    fieldId: "BE-005",
    category: "Négociation",
    title: "Répondre à une offre immobilière trop basse",
    searchTitle: "Offre immobilière trop basse : réponse et stratégie",
    description: "Comment répondre à une offre jugée trop basse : protéger la négociation, clarifier les conditions et préparer la contre-proposition.",
    question: "Que faire quand le vendeur juge l’offre beaucoup trop basse ?",
    diagnosis: "Une réaction émotionnelle immédiate peut fermer une négociation encore utile. Avant de répondre, il faut séparer le montant, les conditions et la solidité de l’acquéreur.",
    recommendation: "Transformer le refus en contre-proposition argumentée avec une durée claire.",
    immediateAction: "Appeler le vendeur avec une lecture factuelle de l’offre et définir son seuil, ses conditions acceptables et la marge de mouvement.",
    steps: [
      "Vérifier le montant, les conditions et la durée de validité.",
      "Identifier ce qui est réellement inacceptable pour le vendeur.",
      "Choisir entre refus motivé, contre-proposition ou demande d’amélioration.",
      "Répondre dans le délai sans révéler inutilement la position minimale du vendeur."],
    message: "Bonjour [Prénom], merci pour votre offre. Les vendeurs l’ont étudiée avec attention. À ce stade, le montant ne leur permet pas d’avancer, mais ils restent ouverts à une proposition revue. Si votre intérêt est confirmé, je peux échanger avec vous aujourd’hui sur les éléments qui permettraient de rapprocher les positions.",
    followUp: { when: "Le jour même", objective: "Conserver l’acquéreur dans la discussion et obtenir une position améliorée." },
    mistakes: ["Transmettre un refus sec sans ouvrir de suite.", "Négocier avant d’avoir clarifié les conditions.", "Inventer une autre offre ou une urgence."],
  },
  {
    slug: "preparer-rendez-vous-estimation-immobiliere",
    fieldId: "BE-007",
    category: "Rendez-vous",
    title: "Préparer un rendez-vous d’estimation immobilière",
    searchTitle: "Rendez-vous d’estimation : checklist pour agent immobilier",
    description: "La préparation utile avant un rendez-vous vendeur : objectif, questions, preuves, objections et prochaine décision.",
    question: "Que préparer avant un rendez-vous d’estimation pour augmenter ses chances d’obtenir le mandat ?",
    diagnosis: "Une estimation seule ne suffit pas. Le vendeur évalue aussi la compréhension de son projet, la crédibilité de la méthode et la qualité du suivi proposé.",
    recommendation: "Préparer le rendez-vous comme une décision à faciliter, pas comme une présentation à réciter.",
    immediateAction: "Écrire l’objectif du vendeur, trois questions indispensables, deux preuves de méthode et la prochaine décision souhaitée.",
    steps: ["Clarifier le projet, le délai et les contraintes du vendeur.", "Préparer les éléments de comparaison réellement pertinents.", "Anticiper les objections sur le prix, les honoraires et l’exclusivité.", "Terminer par un plan d’action daté."],
    message: "Avant notre rendez-vous, pouvez-vous me confirmer votre calendrier idéal et le principal point sur lequel vous souhaitez être rassuré ? Je pourrai ainsi concentrer notre échange sur votre décision plutôt que sur une présentation générale.",
    followUp: { when: "Deux heures avant le rendez-vous", objective: "Arriver avec un objectif et une prochaine décision explicites." },
    mistakes: ["Présenter trop d’informations avant d’avoir compris le projet.", "Utiliser des comparables non expliqués.", "Quitter le rendez-vous sans prochaine étape datée."],
  },
  {
    slug: "annonce-immobiliere-aucun-contact",
    fieldId: "BE-008",
    category: "Mise en vente",
    title: "Une annonce immobilière ne génère aucun contact",
    searchTitle: "Annonce immobilière sans contact : diagnostic en 5 étapes",
    description: "Diagnostiquer une annonce immobilière qui ne génère ni appels ni visites avant de modifier au hasard le texte ou le prix.",
    question: "Que vérifier lorsqu’une annonce immobilière ne reçoit aucun contact ?",
    diagnosis: "L’absence de contact est un signal de positionnement. Elle peut venir du prix, de la première photo, du titre, d’informations manquantes, de la diffusion ou d’un mauvais ciblage.",
    recommendation: "Auditer le parcours dans l’ordre où l’acquéreur le voit : apparition, clic, compréhension, confiance, action.",
    immediateAction: "Comparer la miniature, le titre, le prix et les trois premières informations avec cinq biens concurrents visibles au même moment.",
    steps: ["Vérifier la visibilité réelle et la qualité de la miniature.", "Contrôler la cohérence prix-positionnement.", "Réécrire le début de l’annonce autour de la cible et du bénéfice principal.", "Vérifier les informations obligatoires avant republication.", "Mesurer les réactions pendant une période courte et décider."],
    message: "Bonjour [Prénom], l’annonce ne produit pas encore le niveau de demande attendu. J’ai isolé les points qui peuvent limiter les contacts et préparé un plan de correction par ordre d’impact. Je vous propose un point court pour décider ensemble des modifications à lancer aujourd’hui.",
    followUp: { when: "Après 48 à 72 heures de nouvelle diffusion", objective: "Comparer les nouveaux signaux et décider du prochain ajustement." },
    mistakes: ["Modifier simultanément tous les éléments sans pouvoir mesurer l’effet.", "Allonger le texte sans améliorer l’ouverture.", "Ignorer les informations réglementaires ou les incohérences du dossier."],
  },
  {
    slug: "peb-annonce-immobiliere-wallonie",
    fieldId: "BE-020",
    category: "Conformité",
    title: "PEB et annonce immobilière en Wallonie",
    searchTitle: "PEB dans une annonce immobilière en Wallonie : checklist",
    description: "Checklist opérationnelle PEB avant la publication d’une annonce de vente ou location en Wallonie, avec source officielle vérifiée.",
    question: "Peut-on publier une annonce immobilière en Wallonie sans certificat PEB ?",
    diagnosis: "Le PEB n’est pas un simple détail à ajouter plus tard. Il conditionne la préparation de la publicité et les informations à communiquer dans le parcours de vente ou de location.",
    recommendation: "Bloquer la diffusion publique tant que le certificat et les mentions à reprendre n’ont pas été vérifiés sur la source officielle applicable au bien.",
    immediateAction: "Identifier la région du bien, récupérer le certificat valable et contrôler les indicateurs à intégrer avant publication.",
    steps: ["Confirmer que le bien relève bien de la Wallonie.", "Vérifier la disponibilité et la validité du certificat.", "Extraire les indicateurs demandés pour le support publicitaire.", "Faire un dernier contrôle avant la mise en ligne."],
    message: "Bonjour [Prénom], pour sécuriser la mise en ligne, il nous manque encore la vérification du certificat PEB et des mentions à reprendre dans la publicité. Dès réception du document, je finalise le contrôle et la diffusion.",
    followUp: { when: "Avant toute mise en ligne", objective: "Publier uniquement après contrôle du document et des mentions." },
    mistakes: ["Utiliser une valeur transmise oralement.", "Confondre les exigences régionales.", "Recopier les mentions sans vérifier le certificat correspondant au bien."],
    source: { title: "Certificat PEB : quoi, quand, comment ?", authority: "Service public de Wallonie", url: "https://energie.wallonie.be/home/performance-energetique-des-batiments/batiments-residentiels/achat-vente-location/obligations/certificat-peb--quoi--quand--comment.html", checkedAt: "2026-07-17" },
  },
  {
    slug: "relancer-client-immobilier-indecis",
    fieldId: "BE-009",
    category: "Relance",
    title: "Relancer un client immobilier indécis",
    searchTitle: "Relance client immobilier indécis : message et timing",
    description: "Un plan de relance simple pour faire avancer un client qui dit devoir réfléchir, sans pression ni message générique.",
    question: "Comment relancer un client qui dit « je dois réfléchir » ?",
    diagnosis: "Cette phrase cache souvent une objection non dite, une décision à plusieurs ou l’absence d’un prochain jalon clair.",
    recommendation: "Ne pas demander simplement si le client a réfléchi. Identifier la décision qu’il doit prendre et proposer une aide précise.",
    immediateAction: "Envoyer une question courte qui lui permet de nommer le point encore bloquant.",
    steps: ["Rappeler la décision concernée.", "Nommer deux ou trois hésitations possibles sans présumer.", "Proposer un échange bref ou une information ciblée.", "Fixer la prochaine date seulement si le projet reste actif."],
    message: "Bonjour [Prénom], vous souhaitiez prendre du recul concernant [décision]. Pour vous aider utilement, quel point mérite encore d’être clarifié : le prix, le calendrier ou une caractéristique du bien ? Je vous réponds précisément, sans vous relancer inutilement.",
    followUp: { when: "À la date convenue, ou sous 48 heures si aucune date n’a été fixée", objective: "Faire émerger le véritable frein et décider du suivi." },
    mistakes: ["Envoyer « avez-vous réfléchi ? » sans contexte.", "Créer une fausse urgence.", "Continuer les relances sans statut ni date."],
  },
  {
    slug: "compte-rendu-visite-vendeur",
    fieldId: "BE-036",
    category: "Suivi vendeur",
    title: "Faire un compte rendu de visite au vendeur",
    searchTitle: "Compte rendu de visite immobilier : structure et exemple",
    description: "Une structure de compte rendu de visite utile au vendeur : faits, objections, signal de marché, action et prochaine décision.",
    question: "Que doit contenir un bon compte rendu de visite immobilière ?",
    diagnosis: "Une liste de commentaires bruts rassure rarement le vendeur. Le compte rendu doit transformer les réactions en information exploitable sans surinterpréter une seule visite.",
    recommendation: "Séparer les faits, les réactions répétées et la recommandation de l’agent.",
    immediateAction: "Résumer chaque visite en quatre lignes : profil, intérêt, frein, prochaine action.",
    steps: ["Décrire les faits sans identifier inutilement les visiteurs.", "Regrouper les objections qui se répètent.", "Distinguer un signal isolé d’une tendance.", "Proposer une action et une date de réévaluation."],
    message: "Bonjour [Prénom], voici le point après les visites de cette semaine. Les réactions positives concernent [éléments]. Le frein qui revient est [frein]. À ce stade, je recommande [action] et je vous propose de mesurer son effet jusqu’à [date] avant la prochaine décision.",
    followUp: { when: "Le jour même ou lors du point vendeur prévu", objective: "Maintenir la confiance et transformer les retours en décision." },
    mistakes: ["Transmettre des commentaires blessants sans analyse.", "Promettre une offre après un simple intérêt.", "Attendre que le vendeur demande des nouvelles."],
  },
];

export function getSeoSituation(slug: string) {
  return seoSituations.find((situation) => situation.slug === slug);
}
